// front_end-frameworks/vue/src/components/ui/Badge.vue
<script setup>
import { Sparkle } from 'lucide-vue-next';

// Définition des props (remplace PropTypes)
defineProps({
  text: {
    type: String,
    required: true
  },
  className: {
    type: String,
    default: ''
  }
});
</script>

<template>
  <span :class="['inline-flex items-center gap-2 px-4 py-2 text-xs text-violet-300 rounded-full border border-violet-500/20 bg-violet-500/10', className]">
    <Sparkle class="w-1.5 h-1.5 fill-current" />
    {{ text }}
    <Sparkle class="w-1.5 h-1.5 fill-current" />
  </span>
</template>

// front_end-frameworks/react/src/components/ui/Badge.jsx
import { Astroid } from 'lucide-react';
import PropTypes from 'prop-types';

const Badge = ({ text, className = '' }) => {
  return (
    <span className={`inline-flex items-center gap-2 px-4 py-2 text-xs text-violet-300 rounded-full border border-violet-500/20 bg-violet-500/10 ${className}`}>
      <Astroid className="w-1.5 h-1.5 fill-current" />
      {text}
      <Astroid className="w-1.5 h-1.5 fill-current" />
    </span>
  );
};

Badge.propTypes = {
  text: PropTypes.string.isRequired,
  className: PropTypes.string,
};

export default Badge;
