// front_end-frameworks/svelte/src/components/ui/Button.svelte
<script>
  import { ArrowRight } from 'lucide-svelte';

  // Props
  export let text;
  export let href;
  export let variant = 'primary';
  export let showIcon = false;

  // Styles de base et spécifiques
  const baseStyle = "flex items-center justify-center gap-2 px-4 py-2 font-semibold text-white rounded-md transition-all duration-200";
  const primaryStyle = "bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40";
  const secondaryStyle = "border border-slate-800 bg-slate-950 hover:bg-slate-900";

  // Valeur dérivée/calculée grâce à la syntaxe $:
  $: variantStyle = variant === 'primary' ? primaryStyle : secondaryStyle;
</script>

<a href={href} class="{baseStyle} {variantStyle}">
  {text}

  {#if showIcon}
    <ArrowRight class="w-5 h-5" />
  {/if}
</a>

// front_end-frameworks/react/src/components/ui/Button.jsx
import { ArrowRight } from 'lucide-react';
import PropTypes from 'prop-types';


const Button = ({ text, href, variant = 'primary', showIcon = false }) => {
  // Styles de base communs aux deux boutons
  const baseStyle = "flex items-center justify-center gap-2 px-4 py-2 font-semibold text-white rounded-md transition-all duration-200";
  
  // Styles spécifiques
  const primaryStyle = "bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40";
  const secondaryStyle = "border border-slate-800 bg-slate-950 hover:bg-slate-900";

  return (
    <a 
      href={href} 
      className={`${baseStyle} ${variant === 'primary' ? primaryStyle : secondaryStyle}`}
    >
      {text}
      {/* N'affiche l'icône que si showIcon est true */}
      {showIcon && <ArrowRight className="w-5 h-5" />}
    </a>
  );
};

Button.propTypes = {
  text: PropTypes.string.isRequired, // Le texte du bouton
  href: PropTypes.string.isRequired, // Le lien (#Started, etc.)
  variant: PropTypes.oneOf(['primary', 'secondary']), // Le style (violet ou sombre)
  showIcon: PropTypes.bool, // Afficher la flèche (true) ou non (false)
};

export default Button;
