// front_end-frameworks/svelte/src/components/cards/InsightCard.svelte
<script>
  export let insight;
  export let index;

  // On utilise $: pour que isFeatured se mette à jour si l'index vient à changer
  $: isFeatured = index === 0;
</script>

<div 
  class="group relative rounded-3xl border border-slate-800 bg-slate-950 overflow-hidden hover:border-violet-500/30 transition-all duration-300 min-h-[350px] md:min-h-[400px] flex flex-col justify-end {isFeatured ? 'md:col-span-2' : ''}"
>
  <!-- 1. L'IMAGE EN ARRIÈRE-PLAN -->
  <img 
    src={insight.image} 
    alt={insight.title} 
    class="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 z-0"
  />

  <!-- 2. LE DÉGRADÉ SOMBRE (Pour que le texte blanc soit lisible sur l'image) -->
  <div class="absolute inset-0 bg-gradient-to-t from-black via-black/80 to-transparent z-10"></div>

  <!-- 3. LE TEXTE -->
  <div class="relative z-20 p-8 flex flex-col items-start mt-auto">
    
    <!-- Category -->
    <span class="px-4 py-1.5 rounded-full border border-violet-500/30 bg-violet-500/10 text-violet-300 text-xs tracking-wider mb-4 backdrop-blur-sm">
      {insight.category}
    </span>
    
    <!-- Titre -->
    <h3 class="text-xl md:text-2xl font-bold text-white mb-3">
      {insight.title}
    </h3>
    
    <!-- Description -->
    <p class="text-slate-500 text-sm leading-relaxed">
      {insight.description}
    </p>
  </div>
  
</div>

// front_end-frameworks/react/src/components/InsightCard.jsx
// src/components/InsightCard.jsx
import React from 'react';


const InsightCard = ({ insight, index }) => {
  const isFeatured = index === 0;

  return (
    <div 
      // Si c'est le 1er (isFeatured), on lui dit de prendre 2 colonnes (md:col-span-2) et de s'afficher à l'horizontale (md:flex)
      className={`group rounded-3xl border border-slate-800 bg-slate-950 overflow-hidden hover:border-violet-500/30 transition-all duration-300 ${
        isFeatured ? 'md:col-span-2 md:flex' : ''
      }`}
    >
      {/* image */}
      <div className={`overflow-hidden ${isFeatured ? 'md:w-1/2' : 'h-48'}`}>
        <img 
          src={insight.image} 
          alt={insight.title} 
          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
        />
      </div>

      {/*  text */}
      <div className={`p-8 ${isFeatured ? 'md:w-1/2 flex flex-col justify-center' : ''}`}>
        <span className="text-violet-400 text-xs font-bold uppercase tracking-wider mb-2 block">
          {insight.category}
        </span>
        <h3 className="text-xl md:text-2xl font-bold text-white mb-3">
          {insight.title}
        </h3>
        <p className="text-slate-400 text-sm leading-relaxed">
          {insight.description}
        </p>
      </div>
      
    </div>
  );
};

export default InsightCard;
