// front_end-frameworks/svelte/src/components/layout/Header.svelte
<script>
  import Logo from '../ui/brandLogo.svelte';
</script>

<header class="fixed top-0 w-full z-50 bg-slate-950 border-b border-slate-950 text-white py-4">
  <div class="w-full mx-auto px-6 md:px-12 lg:px-20 h-4 flex items-center justify-between">
    <div>
      <Logo />
    </div>
    <div class="flex items-center gap-8">
      <nav class="hidden md:block">
        <ul class="flex space-x-8 font-medium">
          <li>
            <a href="#about-section" class="text-sm text-slate-500 hover:text-violet-400 transition-colors">About</a>
          </li>
          <li>
            <a href="#features-section" class="text-sm text-slate-500 hover:text-violet-400 transition-colors">Features</a>
          </li>
          <li>
            <a href="#insights-section" class="text-sm text-slate-500 hover:text-violet-400 transition-colors">Insights</a>
          </li>
          <li>
            <a href="#contact-section" class="text-sm text-slate-500 hover:text-violet-400 transition-colors">Contact</a>
          </li>
        </ul>
      </nav>

      <div>
        <a 
          href="#signup" 
          class="px-3 py-1.5 font-semibold rounded-md text-sm text-white bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40"
        >
          Enroll now
        </a>
      </div>
    </div>
  </div>
</header>

// front_end-frameworks/react/src/components/layout/Header.jsx
import Logo from '../ui/brandLogo';

const Header = () => {
  return (
    <header className="fixed top-0 w-full z-50 bg-slate-950 border-b border-slate-950 text-white py-4">
      <div className="w-full mx-auto px-6 md:px-12 lg:px-20 h-4 flex items-center justify-between">
          <div>
            <Logo />
          </div>
        <div className="flex items-center gap-8">
          <nav className="hidden md:block">
            <ul className="flex space-x-8 font-medium">
              <li>
                <a href="#about-section" className="text-sm text-slate-500 hover:text-violet-400 transition-colors">About</a>
              </li>
              <li>
                <a href="#features-section" className="text-sm text-slate-500 hover:text-violet-400 transition-colors">Features</a>
              </li>
              <li>
                <a href="#insights-section" className="text-sm text-slate-500 hover:text-violet-400 transition-colors">Insights</a>
              </li>
              <li>
                <a href="#contact-section" className="text-sm text-slate-500 hover:text-violet-400 transition-colors">Contact</a>
              </li>
            </ul>
          </nav>

          <div>
            <a 
              href="#signup" 
              className="px-3 py-1.5 font-semibold rounded-md text-sm text-white bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40"
            >
              Enroll now
            </a>
          </div>
        </div>

      </div>
    </header>
  );
};

export default Header;
