// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from './components/layout/Header.svelte'
  import Footer from './components/layout/Footer.svelte'
  import Hero from './components/sections/Hero.svelte';
  import About from './components/sections/About.svelte'
  import Feature from './components/sections/Feature.svelte';
  import Insights from './components/sections/Insights.svelte';
  import Contact from './components/sections/Contact.svelte';
</script>

<section id="center" class="min-h-screen bg-slate-950 flex flex-col text-white">
  <Header />
  <main class="flex-1">
    <Hero />
    <About />
    <Feature />
    <Insights />
    <Contact />
    <Footer />
  </main>

</section>

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from './components/layout/Header.vue'
import Hero from './components/sections/Hero.vue';
import About from './components/sections/About.vue';
import Features from './components/sections/Features.vue';
import Insights from './components/sections/Insights.vue';
import Contact from './components/sections/Contact.vue';
import Footer from './components/layout/Footer.vue';
</script>

<template>
  <div class="bg-slate-950 min-h-screen">
    <Header />
    <main>
      <Hero />
      <About />
      <Features />
      <Insights />
      <Contact />
      <Footer />
    </main>
  </div>
</template>
