// front_end-frameworks/react/src/App.jsx
import Header from './components/layout/Header';
import './global.css';
import Hero from './components/sections/Hero';
import About from './components/sections/About';
import Features from './components/sections/Features';
import Insights from './components/sections/Insights';
import Contact from './components/sections/Contact';
import Footer from './components/layout/Footer';

function App() {
  return (
    <div className="min-h-screen bg-black flex flex-col">
      <Header />
      <main className="flex-1">
        <Hero />
        <About />
        <Features />
        <Insights />
        <Contact />
        <Footer />
      </main>



    </div>
  );
}

export default App;

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from './components/layout/Header.vue'
import Hero from './components/sections/Hero.vue';
import About from './components/sections/About.vue';
import Features from './components/sections/Features.vue';
import Insights from './components/sections/Insights.vue';
import Contact from './components/sections/Contact.vue';
import Footer from './components/layout/Footer.vue';
</script>

<template>
  <div class="bg-slate-950 min-h-screen">
    <Header />
    <main>
      <Hero />
      <About />
      <Features />
      <Insights />
      <Contact />
      <Footer />
    </main>
  </div>
</template>
